import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { Header, List } from 'semantic-ui-react'

const Home: NextPage = () => {
  const [activities, setActivities] = useState([])

  useEffect(() => {
    axios.get('https://localhost:44392/api/Activities').then(res => {
      console.log(res.data)
      setActivities(res.data)
    })
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header as="h2" icon="users" content="Reactivities" />
        <List>
          {activities.map((activity: any) => (
            <List.Item key={activity.id}>
              <h2>{activity.name}</h2>
              <p>{activity.description}</p>
            </List.Item>
          ))}
        </List>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
